#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NSU.Droid.Resource", IsApplication=true)]

namespace NSU.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.3.0.26")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int font = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fontProviderCerts = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderFetchStrategy = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderFetchTimeout = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderPackage = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderQuery = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontStyle = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public const int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int notification_action_color_filter = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int notification_icon_bg_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int notification_material_background_media_default_color = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int primary_text_default_material_dark = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ripple_material_light = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int secondary_text_default_material_dark = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int secondary_text_default_material_light = 2130903046;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_action_icon_size = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_action_text_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_big_circle_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_content_margin_start = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_large_icon_height = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_large_icon_width = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_right_icon_size = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_right_side_padding_top = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_small_icon_background_padding = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_small_icon_size_as_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_subtext_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_top_pad = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_top_pad_large_text = 2130968595;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int bg = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int btnGraph = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int btnSettings = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int button_shape = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int caution_sign = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int ComfortZone_shape = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int CZTermometras = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int header_gradient = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int heat_floor = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int heat_floor_black = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int heat_floor_blue = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int heat_floor_green = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int heat_floor_orange = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int heat_floor_red = 2131034125;
			
			// aapt resource value: 0x7F050011
			public const int Icon = 2131034129;
			
			// aapt resource value: 0x7F05000E
			public const int ic_add_user = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int ic_icon = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int ic_user = 2131034128;
			
			// aapt resource value: 0x7F050012
			public const int main_container_shape = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_action_background = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_bg = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int notification_bg_low = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notification_bg_low_normal = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int notification_bg_low_pressed = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int notification_bg_normal = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int notification_bg_normal_pressed = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int notification_icon_background = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int notification_template_icon_bg = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int notification_template_icon_low_bg = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int notification_tile_bg = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int notify_panel_notification_icon_bg = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int NSU_icon_blue = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int NSU_icon_brown = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int NSU_icon_green = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int NSU_icon_grey = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int NSU_icon_red = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int NSU_icon_yellow = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int Ok_Icon_32 = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int sidewindow_shape = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int temp_label_shape = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int top_bootom_border = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int UIImages_akumuliacine = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int UIImages_boileris = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int UIImages_cirkuliacinis1 = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int UIImages_cirkuliacinis2 = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int UIImages_cirkuliacinis3 = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int UIImages_cirkuliacinis4 = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int UIImages_grindys = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int UIImages_house = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int UIImages_house_1aukstas_off = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int UIImages_house_1aukstas_on = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int UIImages_house_2aukstas_off = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int UIImages_house_2aukstas_on = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int UIImages_house_rusys_off = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int UIImages_house_rusys_onn = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int UIImages_kaminas = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int UIImages_karstas_vanduo_off = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int UIImages_karstas_vanduo_on = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int UIImages_katilas = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int UIImages_kolektorius = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int UIImages_ladomatas = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int UIImages_radiatorius = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int UIImages_saule = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int UIImages_snaige = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int UIImages_temp_down = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int UIImages_temp_up = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int UIImages_trisakis1 = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int UIImages_trisakis2 = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int UIImages_trisakis3 = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int UIImages_trisakis4 = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int UIImages_unknown = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int UIImages_ventiliatorius2 = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int window_shape = 2131034184;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F06000A
			public const int action0 = 2131099658;
			
			// aapt resource value: 0x7F06000F
			public const int actions = 2131099663;
			
			// aapt resource value: 0x7F06000B
			public const int action_container = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int action_divider = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int action_image = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int action_text = 2131099662;
			
			// aapt resource value: 0x7F060010
			public const int async = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int blocking = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int btn14Days = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int btn1Day = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int btn2Days = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int btn30Days = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int btn7Days = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int btnRefreshPlot = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int btnRegister = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int button1 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int cancel_action = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int chronometer = 2131099675;
			
			// aapt resource value: 0x7F060000
			public const int CZCurrentTemperatureTextView = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int CZHeatFloorImageView = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int CZSettingsImageViewButton = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int CZShowGraphImageViewButton = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int CZTemperatureTextView = 2131099652;
			
			// aapt resource value: 0x7F06001C
			public const int end_padder = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int footer = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int forever = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int header = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int icon = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int icon_group = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int imageView1 = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int info = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int italic = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int line1 = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int line3 = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int linearLayout1 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int linearLayout2 = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int linearLayout3 = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int linearLayoutCentriukas = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int listPlotItems = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int loaderInfoText = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int mainContainer = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int mainWindow = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int media_actions = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int normal = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int notification_background = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int notification_main_column = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int notification_main_column_container = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int pager = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int pager_title_strip = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int progressBar1 = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int reg_host = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int reg_name = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int reg_password = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int reg_port = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int right_icon = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int right_side = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int rootLayout = 2131099709;
			
			// aapt resource value: 0x7F060005
			public const int SGOkButton = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int SGTSNameTextView = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int SGwebView = 2131099655;
			
			// aapt resource value: 0x7F06003E
			public const int sideWindow = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int status_bar_latest_event_content = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int tag_transition_group = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int text = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int text2 = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int textView1 = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int time = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int title = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int webView = 2131099718;
			
			// aapt resource value: 0x7F060008
			public const int WILaukoTempTextView = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int WIPozemioTempTextView = 2131099657;
			
			// aapt resource value: 0x7F060047
			public const int wvWeatherInfoGrafikas = 2131099719;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int google_play_services_version = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int ComfortZone = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int InfoScreen = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int Loader = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int Login = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int Main = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_action = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_action_tombstone = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_media_action = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_media_cancel_action = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_template_big_media = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int notification_template_big_media_custom = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int notification_template_big_media_narrow = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int notification_template_big_media_narrow_custom = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int notification_template_custom_big = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int notification_template_icon_group = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int notification_template_lines_media = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int notification_template_media = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int notification_template_media_custom = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int notification_template_part_chronometer = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int notification_template_part_time = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int nsusystem = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int plots = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int SensorGraph = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int tab = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int testinis = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int WeatherInfo = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int windows = 2131230746;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int common_google_play_services_unknown_issue = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int firebase_database_url = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int gcm_defaultSenderId = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int google_storage_bucket = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int hello = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int status_bar_notification_info_overflow = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int strBadHost = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int strBadUsrNamePassword = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int strConnectTimeoutTitle = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int strLoginErrorTitle = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int strPassword = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int strPlotBtn14DaysText = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int strPlotBtn1DayText = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int strPlotBtn2DaysText = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int strPlotBtn30DaysText = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int strPlotBtn7DaysText = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int strPlotBtnRefresh = 2131296273;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Info_Media = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Line2 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int TextAppearance_Compat_Notification_Media = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int TextAppearance_Compat_Notification_Time = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int TextAppearance_Compat_Notification_Time_Media = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int TextAppearance_Compat_Notification_Title_Media = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int Widget_Compat_NotificationActionContainer = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int Widget_Compat_NotificationActionText = 2131361803;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006 }
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x7F010000,0x7F010007,0x7F010008 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771968,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
